export const appStrings = {
  yourNote: "your_note",
  addNote: "add_note",
  logOut: "logout",
  language: "language",
  email: "email",
  password: "password",
  login: "login",
  signup: "signup",
  createAccount: "create_account",
  forgotPassword: "forgot_password",
  username: "username",
  update: "update",
  delete: "delete",
  close: "close",
};
